
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 27 20:48:41 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 20;
  public static final int IDENT = 17;
  public static final int PLUS = 10;
  public static final int RBRACE = 4;
  public static final int RPAREN = 7;
  public static final int EQUAL = 8;
  public static final int SEMI = 5;
  public static final int DECREMENT = 28;
  public static final int RETURN = 9;
  public static final int MODULO = 25;
  public static final int LPAREN = 6;
  public static final int LBRACE = 3;
  public static final int LSQUAREBRACKET = 19;
  public static final int COMMA = 11;
  public static final int EOF = 0;
  public static final int NUMBER = 14;
  public static final int CHARCONST = 15;
  public static final int DIV = 23;
  public static final int INCREMENT = 27;
  public static final int PROG = 2;
  public static final int MINUS = 24;
  public static final int CONST = 18;
  public static final int PRINT = 12;
  public static final int error = 1;
  public static final int NEW = 21;
  public static final int RSQUAREBRACKET = 26;
  public static final int MUL = 22;
  public static final int VOID = 13;
  public static final int BOOLCONST = 16;
}

